### ISSUE TITLE
Obtuse error thrown when uninstall a missing package.

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppetlabs-package#74]
When attempting to uninstall a package that doesn't exist, a really bad error messages is thrown e.g.

```
Task exited 1:\nC:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/provider/package/windows.rb:72:in `uninstall': undefined method `uninstall_command' for nil:NilClass (NoMethodError)\n\tfrom C:/ProgramData/PuppetLabs/pxp-agent/tasks-cache/e1afed840a840b9f8eb316c1c35da96489d0007599efe99c5fe2b9a7cb8e0db2/init.rb:39:in `uninstall'\n\tfrom C:/ProgramData/PuppetLabs/pxp-agent/tasks-cache/e1afed840a840b9f8eb316c1c35da96489d0007599efe99c5fe2b9a7cb8e0db2/init.rb:65:in `<main>'\n",
```

This is because https://github.com/puppetlabs/puppetlabs-package/blob/master/tasks/init.rb#L37 always assumes that the provider is not null.

However, depending on the package provider the provider creation call at https://github.com/puppetlabs/puppetlabs-package/blob/master/tasks/init.rb#L61 can return null.

**Comment by glennsarti** [comment]
Nearly 4 years old ...
